import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { buildApp } from '../src/app.js';
import { Store } from '../src/store.js';
import type { Config } from '../src/config.js';
import type { Dataset, RouteRequest } from '../src/schemas.js';
const config:Config={databasePath:':memory:',demoMode:false,production:false,host:'127.0.0.1',port:4101,jwtAudience:'authenticated',adminSubjects:[],corsOrigins:['https://localhost'],devUserToken:'u'.repeat(40),devAdminToken:'a'.repeat(40)};
const data=JSON.parse(readFileSync(new URL('../data/wolgye1.dataset.json',import.meta.url),'utf8')) as Dataset;
test('Android production API exposes real coverage and verified identity, never preview sessions',async t=>{
  const store=new Store(':memory:');store.importDataset(data);const app=await buildApp(config,{store});t.after(async()=>{await app.close();store.close();});
  const coverage=await app.inject('/api/v1/map/coverage');assert.equal(coverage.statusCode,200);assert.equal(coverage.json().data.nodes.length,1783);assert.equal(coverage.json().data.boundary.type,'Polygon');
  const revision=store.revision();const notices=await app.inject('/api/v1/construction-notices');
  assert.equal(notices.statusCode,200);assert.equal(notices.json().data.available,true);
  assert.ok(notices.json().data.items.length>0);assert.equal(store.revision(),revision);assert.equal(store.constructions().length,0);
  assert.equal((await app.inject('/api/v1/me')).statusCode,401);
  const resident=await app.inject({url:'/api/v1/me',headers:{authorization:'Bearer '+config.devUserToken}});assert.deepEqual(resident.json().data,{subject:'dev-user',admin:false});
  assert.equal((await app.inject({method:'POST',url:'/preview/session',payload:{role:'operator'}})).statusCode,404);
  const preflight=await app.inject({method:'OPTIONS',url:'/api/v1/routes/search',headers:{origin:'https://localhost','access-control-request-method':'POST'}});assert.equal(preflight.headers['access-control-allow-origin'],'https://localhost');
});
test('real phone flow: route, save, report replay, construction block, resolve and replan',async t=>{
  const store=new Store(':memory:');store.importDataset(data);const app=await buildApp(config,{store});t.after(async()=>{await app.close();store.close();});
  const user={authorization:'Bearer '+config.devUserToken},admin={authorization:'Bearer '+config.devAdminToken};const edge=data.edges[0]!;
  const search:RouteRequest={originNodeId:edge.from,destinationNodeId:edge.to,profile:'WALK',preference:'NIGHT',avoidStairs:false,maxDetourRatio:1.5};
  const route=async()=> (await app.inject({method:'POST',url:'/api/v1/routes/search',payload:search})).json().data;
  const original=await route();assert.equal(original.status,'OK');
  const saved=await app.inject({method:'POST',url:'/api/v1/me/routes',headers:user,payload:{name:'휴대폰 경로',search}});assert.equal(saved.statusCode,201);
  const p=data.nodes.find(n=>n.id===edge.from)!.position;
  const reportRequest={method:'POST' as const,url:'/api/v1/reports',headers:{...user,'idempotency-key':randomUUID()},payload:{title:'테스트 구간 확인',description:'자동화 테스트이며 실제 공사 제보가 아닙니다.',type:'CONSTRUCTION',position:p}};
  const first=await app.inject(reportRequest),replay=await app.inject(reportRequest);assert.equal(first.statusCode,201);assert.equal(first.json().data.id,replay.json().data.id);assert.equal((await route()).graphVersion,original.graphVersion);
  const at=new Date();const closure=await app.inject({method:'POST',url:'/api/v1/admin/constructions',headers:{...admin,'idempotency-key':randomUUID()},payload:{title:'자동 테스트 통제',description:'메모리 DB의 테스트 통제',position:p,edgeIds:[edge.id],impact:'BLOCK',startsAt:at.toISOString(),source:{type:'FIELD_SURVEY',name:'자동화 테스트 전용',observedAt:at.toISOString(),recheckAt:new Date(+at+3600000).toISOString()},reason:'테스트'}});
  assert.equal(closure.statusCode,201);const blocked=await route();assert.notEqual(blocked.graphVersion,original.graphVersion);for(const r of blocked.routes)assert.ok(!r.edgeIds.includes(edge.id));
  const c=closure.json().data;
  assert.deepEqual(c.segments,[{edgeId:edge.id,coordinates:edge.geometry.map(p=>[p.lng,p.lat])}]);
  const mapItems=(await app.inject('/api/v1/map/items')).json().data.items;
  assert.deepEqual(mapItems.find((i:any)=>i.id===c.id).segments,c.segments);
  assert.ok(!('reason' in c));
  assert.equal((await app.inject('/api/v1/constructions')).json().data[0].impact,'BLOCK');
  const resolved=await app.inject({method:'POST',url:`/api/v1/admin/constructions/${c.id}/resolve`,headers:admin,payload:{expectedVersion:c.version,reason:'테스트 통제 해제'}});assert.equal(resolved.statusCode,200);assert.equal((await route()).routes[0].distanceM,original.routes[0].distanceM);
  assert.ok(!(await app.inject('/api/v1/map/items')).json().data.items.some((i:any)=>i.id===c.id));
});
