import type { Node, Position, Report } from './types';

export const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export const asset=(screen:string,name:string,ext='svg')=>`/figma/current/${screen}-${name}.${ext}`;
export const icon=(screen:string,n:number|string='')=>`<img src="${asset(screen,'imgIcon'+n)}" alt="">`;
export type Place={id:string;name:string;address?:string;position:Position};
export type Preferences={safety:boolean;saved:boolean;notifications:boolean;location:boolean};
const key='chongchong-ui-v2';
export function readLocal<T>(name:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key+name)||'null')??fallback;}catch{return fallback;}}
export function writeLocal(name:string,value:unknown){try{localStorage.setItem(key+name,JSON.stringify(value));}catch{/* Private browsing may disable storage. */}}
export const preferences:Preferences={safety:true,saved:true,notifications:true,location:true,...readLocal<Partial<Preferences>>('preferences',{})};
export function historyPlaces():Place[]{return readLocal<Place[]>('history',[]).filter(p=>p&&typeof p.name==='string'&&p.position&&Number.isFinite(p.position.lat)&&Number.isFinite(p.position.lng)).slice(0,8);}
export function rememberPlace(place:Place){writeLocal('history',[place,...historyPlaces().filter(p=>p.id!==place.id)].slice(0,8));}
export function savedPlaces():Place[]{return readLocal<Place[]>('places',[]);}
export function toggleSavedPlace(place:Place){const rows=savedPlaces();const exists=rows.some(p=>p.id===place.id);writeLocal('places',exists?rows.filter(p=>p.id!==place.id):[place,...rows]);return !exists;}
export const reportTypes:Record<string,string>={ROAD_DAMAGE:'보도 파손',FACILITY_FAILURE:'시설 고장',CONSTRUCTION:'공사',DANGER:'위험 구간',POOR_LIGHTING:'조명 부족',OBSTACLE:'장애물'};
export const reportStatuses:Record<string,string>={PENDING:'확인 중',VERIFIED:'확인 완료',HIDDEN:'숨김'};
const typeStyle=(type:string)=>type==='CONSTRUCTION'?'green':type==='FACILITY_FAILURE'?'blue':['DANGER','POOR_LIGHTING'].includes(type)?'yellow':'pink';
export function timeAgo(value:string){const minutes=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));return minutes<1?'방금 전':minutes<60?`${minutes}분 전`:minutes<1440?`${Math.floor(minutes/60)}시간 전`:new Date(value).toLocaleDateString('ko-KR');}
export function reportCard(r:Report){const style=typeStyle(r.type);return `<button class="report-card ${style}" data-action="report-detail" data-value="${escapeHtml(r.id)}"><span class="report-art">${r.photos?.[0]?`<img class="report-thumb" src="${escapeHtml(r.photos[0])}" alt="제보 현장 사진">`:icon('66-1151',style==='green'?3:style==='blue'?4:style==='yellow'?2:'')}<small>${r.confirmationCount??0}</small></span><span class="report-copy"><span class="tag">${reportTypes[r.type]??r.type}</span><strong>${escapeHtml(r.title)}</strong><span class="report-description">${escapeHtml(r.description)}</span><small>${icon('66-1151',1)} 월계동 · ${timeAgo(r.createdAt)} · ${reportStatuses[r.status]}</small></span></button>`;}
export function reportList(rows:Report[],filter:string,nextOffset:number|null,summary:{verified:number;pending:number}){
  return `<section class="report-summary"><div><small>확인 완료</small><strong>${summary.verified}<span>건</span></strong></div><div><small>확인 중</small><strong>${summary.pending}<span>건</span></strong></div><div class="summary-bear" aria-hidden="true"><i></i><b>• ᴗ •</b></div></section><div class="filters" aria-label="제보 유형">${[['','전체'],['ROAD_DAMAGE','보도·도로'],['DANGER','위험 구간'],['CONSTRUCTION','공사'],['FACILITY_FAILURE','시설 고장']].map(([v,l])=>`<button data-action="filter" data-value="${v}" aria-pressed="${filter===v}" class="${filter===v?'active':''}">${l}</button>`).join('')}</div><div class="report-list">${rows.length?rows.map(reportCard).join(''):'<div class="empty"><strong>아직 등록된 제보가 없어요</strong><br>동네의 작은 변화도 함께 알려주세요.</div>'}</div>${nextOffset!==null?'<button class="secondary" data-action="more-reports">더 보기</button>':''}<button class="report-add" data-action="report-new">${icon('66-1151',5)}제보하기</button>`;
}
export function profileView(user:{nickname?:string;district?:string}|null,counts:{reports:number;confirmations:number}){
  return `<section class="resident"><span class="cloud cloud-one"></span><span class="cloud cloud-two"></span><div class="profile-character"><img src="${asset('66-1005','imgImage','png')}" alt="핑크 날개말 프로필 캐릭터"><span>${icon('66-1005',8)}</span></div><div><h2>${escapeHtml(user?.nickname||'월계길 이웃님')}</h2><p>오늘도 안전한 월계길을 함께 만들어요!</p><button data-action="${user?'logout':'login'}">${user?'로그아웃':'로그인 · 회원가입'}</button></div></section><div class="profile-links"><button class="card" data-action="my-reports"><span class="tile-icon">${icon('66-1005')}</span><strong>내가 쓴 글</strong><b>${counts.reports}</b><span class="tile-chevron">${icon('66-1005',1)}</span></button><button class="card" data-action="my-confirmations"><span class="tile-icon pink">${icon('66-1005',2)}</span><strong>공감한 글</strong><b>${counts.confirmations}</b><span class="tile-chevron">${icon('66-1005',1)}</span></button></div><div class="settings-heading"><h2>${icon('66-1005',3)} 앱 설정</h2></div><div class="settings-card">${[
    ['safety','지도 설정','안전정보와 저장 장소를 지도에 표시',4,''],['notifications','알림','앱 사용 중 주변 안전 소식 알림',5,'peach'],['location','위치 권한','내 위치 기반 지도와 안전 경로 제공',6,'blue']
  ].map(([key,title,description,n,color])=>`<div class="setting-row"><button class="setting-label" data-action="${key==='safety'?'map-settings':key==='location'?'location-info':'notification-info'}"><span class="setting-icon ${color}">${icon('66-1005',n)}</span><span><b>${title}</b><small>${description}</small></span></button><button class="switch" role="switch" aria-label="${title}" aria-checked="${preferences[key as keyof Preferences]}" data-action="preference" data-value="${key}"><span></span></button></div>`).join('')}</div><div class="privacy-note">${icon('66-1005',7)}<span><b>내 정보는 안전하게 보호돼요</b><small>제보 위치는 이웃에게 공개되며, GPS 이동 기록은 저장하지 않아요.</small></span></div><div class="flowers" aria-hidden="true">✿ <span>··········</span> ✦ <span>··········</span> ✿</div><details class="extra-settings"><summary>저장한 장소 · 추가 설정</summary><button class="setting" data-action="saved-places">저장한 장소</button><button class="setting" data-action="tab" data-value="saved">저장한 길</button><button class="setting" data-action="options">이동 조건</button><button class="setting" data-action="night">낮·밤 자동 전환</button><button class="setting" data-action="install">홈 화면에 추가</button><button class="setting" data-action="settings">지도 · 서버 연결</button><button class="setting" data-action="sources">자료 출처와 확인 상태</button></details>`;
}
export function placeRows(rows:Place[],action='recent-place') {return rows.map(p=>`<button class="place-row" data-action="${action}" data-value="${escapeHtml(p.id)}"><span class="place-row-icon">${icon('66-1796',5)}</span><span><b>${escapeHtml(p.name)}</b><small>${escapeHtml(p.address||'월계동 보행망 연결점')}</small></span>${icon('66-1796',6)}</button>`).join('');}
export function searchView(query='',results?:Place[],notice='') {return `<form data-form="place-search" class="place-search"><button type="submit" aria-label="검색">${icon('66-1697',2)}</button><input name="query" aria-label="장소 검색어" placeholder="어디로 갈까요?" value="${escapeHtml(query)}" minlength="2" maxlength="100" required autofocus><button type="button" data-action="search-clear" aria-label="검색어 지우기">×</button></form>${results?`<div class="section-label">검색 결과 <small>${results.length}개</small></div>${notice?`<p class="small">${escapeHtml(notice)}</p>`:''}<div class="place-list">${results.length?placeRows(results,'search-result'):'<p class="empty">검색 결과가 없어요. 다른 장소 이름으로 찾아보세요.</p>'}</div>`:`<div class="section-label">최근 검색 <small>${historyPlaces().length}개</small></div><div class="place-list">${historyPlaces().length?placeRows(historyPlaces()):'<p class="empty">최근 검색한 장소가 없어요.</p>'}<button class="clear-history" data-action="clear-history">전체 삭제</button></div><div class="search-categories">${[['공원',7],['정류장',8],['자전거',9],['안전시설',10]].map(([name,n])=>`<button data-action="category-search" data-value="${name}"><span>${icon('66-1697',n)}</span>${name}</button>`).join('')}</div>`}`;}
export function plannerView(origin:Node|null,destination:Node|null,via:Node[]) {return `<div class="planner-endpoints"><button data-action="pick" data-value="origin"><i></i><small>출발</small><b>${escapeHtml(origin?.name||'출발지를 선택해주세요')}</b></button>${via.map((n,i)=>`<div class="waypoint-row"><button data-action="pick" data-value="via-${i}"><i></i><small>경유</small><b>${escapeHtml(n.name)}</b></button><button data-action="remove-waypoint" data-value="${i}" aria-label="경유지 삭제">×</button></div>`).join('')}<button data-action="pick" data-value="destination"><i></i><small>도착</small><b>${escapeHtml(destination?.name||'어디로 갈까요?')}</b></button><button class="swap" data-action="swap-endpoints" aria-label="출발지와 도착지 바꾸기">${icon('66-1796',2)}</button></div><div class="planner-actions"><button data-action="choose-map">${icon('66-1796',3)}지도에서 선택</button><button data-action="add-waypoint" ${via.length>=3?'disabled':''}>${icon('66-1796',4)}경유지 추가</button></div><div class="section-label">최근 목적지 <small>최근 3개</small></div><div class="place-list">${historyPlaces().length?placeRows(historyPlaces().slice(0,3),'planner-recent'):'<p class="empty">장소를 검색해 목적지를 선택해보세요.</p>'}</div><button class="primary planner-submit" data-action="calculate-route" ${!origin||!destination?'disabled':''}>경로 찾기</button>`;}
export function reportForm(position:Position|null,draft:{type:string;description:string;photos:string[]}) {return `<form data-form="report" class="report-form"><section class="form-card"><h3>위치 선택</h3><div id="report-location-map" class="mini-map" aria-label="제보 위치 지도"><span>${position?'선택 위치를 불러오고 있어요':'제보할 위치를 선택해주세요'}</span></div><div class="location-row"><button type="button" data-action="gps-report">${icon('66-1554',6)}${position?`월계동 · ${position.lat.toFixed(4)}, ${position.lng.toFixed(4)}`:'현재 위치 사용'}</button><button type="button" data-action="report-pick-map">지도에서 선택</button></div></section><fieldset class="form-card report-types"><legend>제보 유형</legend><div>${['ROAD_DAMAGE','FACILITY_FAILURE','CONSTRUCTION','DANGER'].map((v,i)=>`<label><input type="radio" name="type" value="${v}" ${draft.type===v?'checked':''}><span>${icon('66-1554',7+i)}${reportTypes[v]}</span></label>`).join('')}</div></fieldset><section class="form-card"><label for="description">상세 설명</label><textarea id="description" name="description" minlength="10" maxlength="300" required placeholder="어떤 문제인지 자세히 알려주세요.">${escapeHtml(draft.description)}</textarea><small class="character-count"><span id="description-count">${draft.description.length}</span> / 300</small></section><section class="form-card"><h3>사진 첨부 <small>선택 · 최대 2장</small></h3><div class="photo-row"><label class="photo-add" for="report-photos">${icon('66-1554',11)}사진 추가<input id="report-photos" type="file" accept="image/jpeg,image/png,image/webp" multiple ${draft.photos.length>=2?'disabled':''}></label>${draft.photos.map((p,i)=>`<div class="photo-preview"><img src="${escapeHtml(p)}" alt="첨부 사진 ${i+1}"><button type="button" data-action="remove-photo" data-value="${i}" aria-label="사진 ${i+1} 삭제">×</button></div>`).join('')}</div></section><div class="form-error" role="alert"></div><button type="submit" class="primary report-submit">제보 등록하기</button></form>`;}
export async function preparePhoto(file:File):Promise<string>{
  if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw new Error('15MB 이하의 JPG, PNG, WebP 사진을 선택해주세요.');
  const bitmap=await createImageBitmap(file);const scale=Math.min(1,1000/Math.max(bitmap.width,bitmap.height));
  const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d')!.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();
  let quality=.82,result=canvas.toDataURL('image/jpeg',quality);while(result.length>680000&&quality>.3){quality-=.1;result=canvas.toDataURL('image/jpeg',quality);}if(result.length>680000)throw new Error('사진 크기를 줄여 다시 선택해주세요.');return result;
}
